# Generated by Django 3.2.9 on 2022-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_users', '0002_tguser_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='user_id',
            new_name='user',
        ),
    ]
